# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/behovsvurdering
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 80

healthcheck:
  liveness:
    path: behovsvurdering/
  readiness:
    path: behovsvurdering/index.html
    initialDelay: 20

team: oppfolging

alertProfiles:
  - common-java-modules

prometheus:
  enabled: true
  path: behovsvurdering/internal/metrics

resources:
  limits:
    cpu: 3
    memory: 768Mi
  requests:
    memory: 512Mi

fasitResources:
  used:
    - alias: appres.cms
      resourceType: baseUrl
    - alias: appdynamics
      resourceType: applicationproperties