apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: behovsvurdering
  namespace: pto
  cluster: dev-gcp
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/pto-frontend/pto-frontend:19bf5fe1b248bc956db8f716672496202a680d13
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  ingresses:
    - https://behovsvurdering.dev.nav.no
  accessPolicy:
    outbound:
      external:
        - host: pto-proxy.dev.nav.no
  gcp:
    buckets:
      - name: behovsvurdering-dev
        cascadingDelete: true
  env:
    - name: ENFORCE_LOGIN
      value: "true"
    - name: LOGIN_REDIRECT_URL
      value: https://loginservice.dev.nav.no/login?redirect={RETURN_TO_URL}&level=Level4
    - name: OIDC_DISCOVERY_URL
      value: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    - name: OIDC_CLIENT_ID
      value: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5
    - name: TOKEN_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: GCS_BUCKET_NAME
      value: behovsvurdering-dev
    - name: GCS_BUCKET_PREFIX_PATH
      value: build
    - name: JSON_CONFIG
      value: >
        {
          "proxies": [
            { "from": "/proxy", "to": "https://pto-proxy.dev.nav.no", "preserveContextPath": true }
          ]
        }