apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: behovsvurdering
  namespace: {{namespace}}
  cluster: dev-sbs
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/behovsvurdering/behovsvurdering:{{version}}
  liveness:
    path: /internal/isAlive
    initialDelay: 30
  readiness:
    path: /internal/isReady
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  prometheus:
    enabled: true
    path: /internal/metrics
  webproxy: true
  ingresses:
    - https://behovsvurdering-{{namespace}}.dev-sbs.nais.io
  env:
    - AAD_B2C_CLIENTID_USERNAME
    - AAD_B2C_DISCOVERY_URL
    - APPRES_CMS_URL
    - LOGINSERVICE_URL
    - APPRES_CMS_URL
    - UNLEASH_API_URL
    - AKTIVITETSPLAN_URL
    - JOBBSOKERKOMPETANSE_URL
    - ARBEIDSPLASSEN_URL
