apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: behovsvurdering
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/pto-frontend/pto-frontend:3800b289004d9a7d3dafe4dda8ece837afe033da
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi
#  ingresses:
#    - https://behovsvurdering.nav.no
  accessPolicy:
    outbound:
      external:
        - host: pto-proxy.nav.no
  gcp:
    buckets:
      - name: behovsvurdering-prod
        cascadingDelete: false
  env:
    - name: ENFORCE_LOGIN
      value: "true"
    - name: LOGIN_REDIRECT_URL
      value: https://loginservice.nav.no/login?redirect={RETURN_TO_URL}&level=Level4
    - name: OIDC_DISCOVERY_URL
      value: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
    - name: OIDC_CLIENT_ID
      value: 45104d6a-f5bc-4e8c-b352-4bbfc9381f25
    - name: TOKEN_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: GCS_BUCKET_NAME
      value: behovsvurdering-prod
    - name: JSON_CONFIG
      value: >
        {
          "proxies": [
            { "from": "/proxy", "to": "https://pto-proxy.nav.no", "preserveContextPath": true }
          ]
        }