apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: behovsvurdering
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/pto-frontend/pto-frontend:2022.05.06_06.20-7942c207e953
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  ingresses:
    - https://behovsvurdering.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navnob2c.b2clogin.com
  gcp:
    buckets:
      - name: behovsvurdering-prod
        cascadingDelete: false
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: ENFORCE_LOGIN
      value: "true"
    - name: LOGIN_REDIRECT_URL
      value: https://loginservice.nav.no/login?redirect={RETURN_TO_URL}&level=Level4
    - name: TOKEN_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: GCS_BUCKET_NAME
      value: behovsvurdering-prod
    - name: JSON_CONFIG
      value: >
        {
          "proxies": [
            { "from": "/proxy", "to": "http://pto-proxy", "preserveContextPath": true }
          ]
        }