name: Test, build and update
on: push
env:
  CI: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  update-dev:
    name: Upload files to dev GCS
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build application
        run: npm run build
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY_DEV }}
          export_default_credentials: true
      - name: Upload files to GCS
        run: gsutil -m rsync -r build gs://behovsvurdering-dev

  update-prod:
    name: Upload files to prod GCS
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build application
        run: npm run build
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY_PROD }}
          export_default_credentials: true
      - name: Upload files to GCS
        run: gsutil -m rsync -r build gs://behovsvurdering-prod
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Production environment updated
          target_commitish: master
          tag_name: release/prod@${{ github.sha }}
